### ISSUE TITLE
READ.me 应该增加更多这个小程序功能的演示

### ISSUE THREAD

**Issue by JailBreakC** [vikadata/widget-datasheet-operation#1]
这个小程序属于进阶功能演示，不用花费太多篇幅介绍基础安装和运行过程，应当更多的介绍这个小程序实现了对哪些 SDK 功能的使用。激发开发者想象力

**Comment by Niko030303** [comment]
bbs社区有对应的功能录屏，我晚点补充下对应文案再拷到 README
